### ISSUE TITLE
Tiktoken core encoding error

### ISSUE THREAD

**Issue by dickiesanders** [jimmc414/1filellm#13]
Disallowing or allowing special characters does not appear to work.

```thread '<unnamed>' panicked at src/lib.rs:250:33:
called `Result::unwrap()` on an `Err` value: RuntimeError(StackOverflow)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/richard.sanders/Documents/ulterior/1filellm/onefilellm.py", line 605, in <module>
    main()
  File "/Users/richard.sanders/Documents/ulterior/1filellm/onefilellm.py", line 592, in main
    compressed_token_count = get_token_count(compressed_text)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richard.sanders/Documents/ulterior/1filellm/onefilellm.py", line 236, in get_token_count
    tokens = enc.encode(text, disallowed_special=disallowed_special)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richard.sanders/Documents/ulterior/1filellm/.venv/lib/python3.11/site-packages/tiktoken/core.py", line 124, in encode
    return self._core_bpe.encode(text, allowed_special)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: RuntimeError(StackOverflow)```

Suggest adding chunking during the `get_token_count` process.

**Comment by jimmc414** [comment]
Can you provide the URL you were using?

**Comment by jimmc414** [comment]
merged.  Thanks for your work!
