### ISSUE TITLE
time out problem in processing repo

### ISSUE THREAD

**Issue by Learner00100** [jimmc414/1filellm#5]
Traceback (most recent call last):
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7e56c099f250>, 'Connection to api.github.com timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/z-huang/InnerTune/contents/fastlane/metadata/android/es?ref=dev (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7e56c099f250>, 'Connection to api.github.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/surprise/new/new.py", line 348, in <module>
    main()
  File "/home/user/surprise/new/new.py", line 316, in main
    process_github_repo(input_path, output_file)
  File "/home/user/surprise/new/new.py", line 115, in process_github_repo
    process_directory(contents_url, output)
  File "/home/user/surprise/new/new.py", line 79, in process_directory
    process_directory(file["url"], output)
  File "/home/user/surprise/new/new.py", line 79, in process_directory
    process_directory(file["url"], output)
  File "/home/user/surprise/new/new.py", line 79, in process_directory
    process_directory(file["url"], output)
  [Previous line repeated 1 more time]
  File "/home/user/surprise/new/new.py", line 55, in process_directory
    response = requests.get(url, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/surprise/.venv/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/z-huang/InnerTune/contents/fastlane/metadata/android/es?ref=dev (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7e56c099f250>, 'Connection to api.github.com timed out. (connect timeout=None)'))

**Comment by jimmc414** [comment]
It looks like your Connection to github timed out.  I was able to successfully parse https://github.com/z-huang/InnerTune
If this is reproducible please provide the reproduction steps.
```
(jim) C:\python\OneFileRepo>python 1filellm.py
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jim\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Enter the path or URL for ingestion: https://github.com/z-huang/InnerTune
Processing README.md...
Processing app/CMakeLists.txt...
Processing fastlane/metadata/android/en-US/changelogs/10.txt...
Processing fastlane/metadata/android/en-US/changelogs/11.txt...
Processing fastlane/metadata/android/en-US/changelogs/12.txt...
Processing fastlane/metadata/android/en-US/changelogs/13.txt...
Processing fastlane/metadata/android/en-US/changelogs/14.txt...
Processing fastlane/metadata/android/en-US/changelogs/15.txt...
Processing fastlane/metadata/android/en-US/changelogs/16.txt...
Processing fastlane/metadata/android/en-US/changelogs/17.txt...
Processing fastlane/metadata/android/en-US/changelogs/18.txt...
Processing fastlane/metadata/android/en-US/changelogs/19.txt...
Processing fastlane/metadata/android/en-US/changelogs/5.txt...
Processing fastlane/metadata/android/en-US/changelogs/6.txt...
Processing fastlane/metadata/android/en-US/changelogs/7.txt...
Processing fastlane/metadata/android/en-US/changelogs/8.txt...
Processing fastlane/metadata/android/en-US/changelogs/9.txt...
Processing fastlane/metadata/android/en-US/full_description.txt...
Processing fastlane/metadata/android/en-US/short_description.txt...
Processing fastlane/metadata/android/en-US/title.txt...
Processing fastlane/metadata/android/es/full_description.txt...
Processing fastlane/metadata/android/es/short_description.txt...
Processing fastlane/metadata/android/it/full_description.txt...
Processing fastlane/metadata/android/it/short_description.txt...
Processing fastlane/metadata/android/it/title.txt...
Processing fastlane/metadata/android/ja/full_description.txt...
Processing fastlane/metadata/android/ja/short_description.txt...
Processing fastlane/metadata/android/ko/full_description.txt...
Processing fastlane/metadata/android/ko/short_description.txt...
Processing fastlane/metadata/android/pa/full_description.txt...
Processing fastlane/metadata/android/pa/short_description.txt...
Processing fastlane/metadata/android/ru-RU/full_description.txt...
Processing fastlane/metadata/android/ru-RU/short_description.txt...
Processing fastlane/metadata/android/ru-RU/title.txt...
Processing fastlane/metadata/android/tr/full_description.txt...
Processing fastlane/metadata/android/tr/short_description.txt...
Processing fastlane/metadata/android/uk-UA/full_description.txt...
Processing fastlane/metadata/android/uk-UA/short_description.txt...
Processing fastlane/metadata/android/uk-UA/title.txt...
All files processed.
Compressed Token Count: 3234
Uncompressed Token Count: 6405
compressed_output.txt and uncompressed_output.txt have been created in the working directory. Contents of uncompressed_output.txt have been copied to the clipboard.
```

**Comment by Learner00100** [comment]
In your case, text and md is processed.
Check with
allowed_extensions = ['.md','.kt','.java']

**Comment by jimmc414** [comment]
Checked https://github.com/z-huang/InnerTune with
allowed_extensions = ['.md','.kt','.java']
see below.  I believe github is just timing out on you,  so far not seeing a software defect.

(jim) C:\python\OneFileRepo>python 1filellm.py
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jim\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Enter the path or URL for ingestion: https://github.com/z-huang/InnerTune
Processing README.md...
Processing app/src/foss/java/com/zionhuang/music/utils/TranslationHelper.kt...
Processing app/src/foss/java/com/zionhuang/music/utils/Utils.kt...
Processing app/src/full/java/com/zionhuang/music/utils/TranslationHelper.kt...
Processing app/src/full/java/com/zionhuang/music/utils/Utils.kt...
Processing app/src/main/java/com/zionhuang/music/App.kt...
Processing app/src/main/java/com/zionhuang/music/MainActivity.kt...
Processing app/src/main/java/com/zionhuang/music/constants/Dimensions.kt...
Processing app/src/main/java/com/zionhuang/music/constants/MediaSessionConstants.kt...
Processing app/src/main/java/com/zionhuang/music/constants/PreferenceKeys.kt...
Processing app/src/main/java/com/zionhuang/music/constants/StatPeriod.kt...
Processing app/src/main/java/com/zionhuang/music/db/Converters.kt...
Processing app/src/main/java/com/zionhuang/music/db/DatabaseDao.kt...
Processing app/src/main/java/com/zionhuang/music/db/MusicDatabase.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/Album.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/AlbumArtistMap.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/AlbumEntity.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/AlbumWithSongs.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/Artist.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/ArtistEntity.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/Event.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/EventWithSong.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/FormatEntity.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/LocalItem.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/LyricsEntity.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/Playlist.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/PlaylistEntity.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/PlaylistSong.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/PlaylistSongMap.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/PlaylistSongMapPreview.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/RelatedSongMap.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/SearchHistory.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/Song.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/SongAlbumMap.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/SongArtistMap.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/SongEntity.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/SortedSongAlbumMap.kt...
Processing app/src/main/java/com/zionhuang/music/db/entities/SortedSongArtistMap.kt...
Processing app/src/main/java/com/zionhuang/music/di/AppModule.kt...
Processing app/src/main/java/com/zionhuang/music/extensions/CoroutineExt.kt...
Processing app/src/main/java/com/zionhuang/music/extensions/FileExt.kt...
Processing app/src/main/java/com/zionhuang/music/extensions/ListExt.kt...
Processing app/src/main/java/com/zionhuang/music/extensions/MediaItemExt.kt...
Processing app/src/main/java/com/zionhuang/music/extensions/PlayerExt.kt...
Processing app/src/main/java/com/zionhuang/music/extensions/StringExt.kt...
Processing app/src/main/java/com/zionhuang/music/extensions/UtilExt.kt...
Processing app/src/main/java/com/zionhuang/music/lyrics/KuGouLyricsProvider.kt...
Processing app/src/main/java/com/zionhuang/music/lyrics/LyricsEntry.kt...
Processing app/src/main/java/com/zionhuang/music/lyrics/LyricsHelper.kt...
Processing app/src/main/java/com/zionhuang/music/lyrics/LyricsProvider.kt...
Processing app/src/main/java/com/zionhuang/music/lyrics/LyricsUtils.kt...
Processing app/src/main/java/com/zionhuang/music/lyrics/YouTubeLyricsProvider.kt...
Processing app/src/main/java/com/zionhuang/music/lyrics/YouTubeSubtitleLyricsProvider.kt...
Processing app/src/main/java/com/zionhuang/music/models/ItemsPage.kt...
Processing app/src/main/java/com/zionhuang/music/models/MediaMetadata.kt...
Processing app/src/main/java/com/zionhuang/music/models/PersistQueue.kt...
Processing app/src/main/java/com/zionhuang/music/playback/DownloadUtil.kt...
Processing app/src/main/java/com/zionhuang/music/playback/ExoDownloadService.kt...
Processing app/src/main/java/com/zionhuang/music/playback/MediaLibrarySessionCallback.kt...
Processing app/src/main/java/com/zionhuang/music/playback/MusicService.kt...
Processing app/src/main/java/com/zionhuang/music/playback/PlayerConnection.kt...
Processing app/src/main/java/com/zionhuang/music/playback/SleepTimer.kt...
Processing app/src/main/java/com/zionhuang/music/playback/queues/EmptyQueue.kt...
Processing app/src/main/java/com/zionhuang/music/playback/queues/ListQueue.kt...
Processing app/src/main/java/com/zionhuang/music/playback/queues/Queue.kt...
Processing app/src/main/java/com/zionhuang/music/playback/queues/YouTubeAlbumRadio.kt...
Processing app/src/main/java/com/zionhuang/music/playback/queues/YouTubeQueue.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/AutoResizeText.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/BigSeekBar.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/BottomSheet.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/BottomSheetMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/ChipsRow.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/Dialog.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/EmptyPlaceholder.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/GridMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/HideOnScrollFAB.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/IconButton.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/Items.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/Lyrics.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/NavigationTile.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/NavigationTitle.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/PlayingIndicator.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/Preference.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/SearchBar.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/SortHeader.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/shimmer/ButtonPlaceholder.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/shimmer/GridItemPlaceholder.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/shimmer/ListItemPlaceholder.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/shimmer/ShimmerHost.kt...
Processing app/src/main/java/com/zionhuang/music/ui/component/shimmer/TextPlaceholder.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/AddToPlaylistDialog.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/AlbumMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/ArtistMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/LyricsMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/PlayerMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/PlaylistMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/SongMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/YouTubeAlbumMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/YouTubeArtistMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/YouTubePlaylistMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/menu/YouTubeSongMenu.kt...
Processing app/src/main/java/com/zionhuang/music/ui/player/MiniPlayer.kt...
Processing app/src/main/java/com/zionhuang/music/ui/player/PlaybackError.kt...
Processing app/src/main/java/com/zionhuang/music/ui/player/Player.kt...
Processing app/src/main/java/com/zionhuang/music/ui/player/Queue.kt...
Processing app/src/main/java/com/zionhuang/music/ui/player/Thumbnail.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/AccountScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/AlbumScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/HistoryScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/HomeScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/LoginScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/MoodAndGenresScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/NewReleaseScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/Screens.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/StatsScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/YouTubeBrowseScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/artist/ArtistItemsScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/artist/ArtistScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/artist/ArtistSongsScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/library/LibraryAlbumsScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/library/LibraryArtistsScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/library/LibraryPlaylistsScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/library/LibrarySongsScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/playlist/LocalPlaylistScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/playlist/OnlinePlaylistScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/search/LocalSearchScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/search/OnlineSearchResult.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/search/OnlineSearchScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/settings/AboutScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/settings/AppearanceSettings.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/settings/BackupAndRestore.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/settings/ContentSettings.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/settings/PlayerSettings.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/settings/PrivacySettings.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/settings/SettingsScreen.kt...
Processing app/src/main/java/com/zionhuang/music/ui/screens/settings/StorageSettings.kt...
Processing app/src/main/java/com/zionhuang/music/ui/theme/Theme.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/AppBar.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/FadingEdge.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/HorizontalPager.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/LazyGridSnapLayoutInfoProvider.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/NavControllerUtils.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/ScrollUtils.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/ShapeUtils.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/StringUtils.kt...
Processing app/src/main/java/com/zionhuang/music/ui/utils/YouTubeUtils.kt...
Processing app/src/main/java/com/zionhuang/music/utils/CoilBitmapLoader.kt...
Processing app/src/main/java/com/zionhuang/music/utils/ComposeDebugUtils.kt...
Processing app/src/main/java/com/zionhuang/music/utils/DataStore.kt...
Processing app/src/main/java/com/zionhuang/music/utils/StringUtils.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/AccountViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/AlbumViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/ArtistItemsViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/ArtistViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/BackupRestoreViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/HistoryViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/HomeViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/LibraryViewModels.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/LocalPlaylistViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/LocalSearchViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/LyricsMenuViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/MoodAndGenresViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/NewReleaseViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/OnlinePlaylistViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/OnlineSearchSuggestionViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/OnlineSearchViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/StatsViewModel.kt...
Processing app/src/main/java/com/zionhuang/music/viewmodels/YouTubeBrowseViewModel.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/InnerTube.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/YouTube.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/encoder/BrotliEncoder.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/AccountInfo.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/AutomixPreviewVideoRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Badges.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Button.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Context.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Continuation.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Endpoint.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/GridRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Icon.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Menu.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicCardShelfRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicCarouselShelfRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicDescriptionShelfRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicNavigationButtonRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicPlaylistShelfRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicQueueRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicResponsiveListItemRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicShelfRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/MusicTwoRowItemRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/NavigationEndpoint.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/PlaylistPanelRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/PlaylistPanelVideoRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/ResponseContext.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Runs.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/SearchSuggestions.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/SearchSuggestionsSectionRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/SectionListRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Tabs.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/ThumbnailRenderer.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/Thumbnails.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/YTItem.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/YouTubeClient.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/YouTubeLocale.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/body/AccountMenuBody.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/body/BrowseBody.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/body/GetQueueBody.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/body/GetSearchSuggestionsBody.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/body/GetTranscriptBody.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/body/NextBody.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/body/PlayerBody.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/body/SearchBody.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/AccountMenuResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/BrowseResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/GetQueueResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/GetSearchSuggestionsResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/GetTranscriptResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/NextResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/PipedResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/PlayerResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/models/response/SearchResponse.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/AlbumPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/ArtistItemsContinuationPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/ArtistItemsPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/ArtistPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/BrowseResult.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/ExplorePage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/MoodAndGenres.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/NewReleaseAlbumPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/NextPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/PlaylistContinuationPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/PlaylistPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/RelatedPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/SearchPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/SearchSuggestionPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/pages/SearchSummaryPage.kt...
Processing innertube/src/main/java/com/zionhuang/innertube/utils/Utils.kt...
Processing innertube/src/test/java/com/zionhuang/innertube/YouTubeTest.kt...
Processing kugou/src/main/java/com/zionhuang/kugou/KuGou.kt...
Processing kugou/src/main/java/com/zionhuang/kugou/models/DownloadLyricsResponse.kt...
Processing kugou/src/main/java/com/zionhuang/kugou/models/SearchLyricsResponse.kt...
Processing kugou/src/main/java/com/zionhuang/kugou/models/SearchSongResponse.kt...
Processing kugou/src/test/java/Test.kt...
Processing material-color-utilities/src/main/java/com/google/material/color/blend/Blend.java...
Processing material-color-utilities/src/main/java/com/google/material/color/contrast/Contrast.java...
Processing material-color-utilities/src/main/java/com/google/material/color/dislike/DislikeAnalyzer.java...
Processing material-color-utilities/src/main/java/com/google/material/color/dynamiccolor/DynamicColor.java...
Processing material-color-utilities/src/main/java/com/google/material/color/dynamiccolor/ToneDeltaConstraint.java...
Processing material-color-utilities/src/main/java/com/google/material/color/dynamiccolor/TonePolarity.java...
Processing material-color-utilities/src/main/java/com/google/material/color/hct/Cam16.java...
Processing material-color-utilities/src/main/java/com/google/material/color/hct/Hct.java...
Processing material-color-utilities/src/main/java/com/google/material/color/hct/HctSolver.java...
Processing material-color-utilities/src/main/java/com/google/material/color/hct/ViewingConditions.java...
Processing material-color-utilities/src/main/java/com/google/material/color/palettes/CorePalette.java...
Processing material-color-utilities/src/main/java/com/google/material/color/palettes/TonalPalette.java...
Processing material-color-utilities/src/main/java/com/google/material/color/quantize/PointProvider.java...
Processing material-color-utilities/src/main/java/com/google/material/color/quantize/PointProviderLab.java...
Processing material-color-utilities/src/main/java/com/google/material/color/quantize/Quantizer.java...
Processing material-color-utilities/src/main/java/com/google/material/color/quantize/QuantizerCelebi.java...
Processing material-color-utilities/src/main/java/com/google/material/color/quantize/QuantizerMap.java...
Processing material-color-utilities/src/main/java/com/google/material/color/quantize/QuantizerResult.java...
Processing material-color-utilities/src/main/java/com/google/material/color/quantize/QuantizerWsmeans.java...
Processing material-color-utilities/src/main/java/com/google/material/color/quantize/QuantizerWu.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/DynamicScheme.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/Scheme.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/SchemeExpressive.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/SchemeFidelity.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/SchemeMonochrome.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/SchemeNeutral.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/SchemeTonalSpot.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/SchemeVibrant.java...
Processing material-color-utilities/src/main/java/com/google/material/color/scheme/Variant.java...
Processing material-color-utilities/src/main/java/com/google/material/color/score/Score.java...
Processing material-color-utilities/src/main/java/com/google/material/color/temperature/TemperatureCache.java...
Processing material-color-utilities/src/main/java/com/google/material/color/utils/ColorUtils.java...
Processing material-color-utilities/src/main/java/com/google/material/color/utils/MathUtils.java...
Processing material-color-utilities/src/main/java/com/google/material/color/utils/StringUtils.java...
All files processed.
Compressed Token Count: 213421
Uncompressed Token Count: 245072
compressed_output.txt and uncompressed_output.txt have been created in the working directory. Contents of uncompressed_output.txt have been copied to the clipboard.

**Comment by Learner00100** [comment]
Thanks, I will check with my end.
